# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 576e8ca540f289a4a97c6102d45d1a40f5ef7c45a9c9dfb766f594a20e392a2c01f169e1ccf92f3c3cc627acc52586f8fd92296ade7df0b1bb79314b3bd5bc27

test:
  secret_key_base: a0ab35393b202f38af50a07078395f553d65ce99db99d3f4ca3135af3e79ea83702010df5900b8f8831d2b4c5aadf60308ab21b7ac3a6bd0b05b92e782ef43a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
